version: '3.2'
services:
  redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    network_mode: host
    volumes:
      - ./redis/:/bitnami/redis/data
