scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
rule_files:
  - './con.yml'
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']