scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'process_exporter'
    static_configs:
      - targets:
          - 'localhost:9256'
rule_files:
  - './con.yml'
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']